--student id: 30600022
--student name: Enoch Leow
-- Capture run of script in file called ad_schema_output.txt
set echo on
SPOOL ad_schema_output.txt
-- Generated by Oracle SQL Developer Data Modeler 20.4.0.374.0801
--   at:        2021-04-28 15:03:49 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



DROP TABLE appointment CASCADE CONSTRAINTS;

DROP TABLE clinic CASCADE CONSTRAINTS;

DROP TABLE drug CASCADE CONSTRAINTS;

DROP TABLE ownership CASCADE CONSTRAINTS;

DROP TABLE pet CASCADE CONSTRAINTS;

DROP TABLE pettype CASCADE CONSTRAINTS;

DROP TABLE prescription CASCADE CONSTRAINTS;

DROP TABLE procedure CASCADE CONSTRAINTS;

DROP TABLE service CASCADE CONSTRAINTS;

DROP TABLE specialisation CASCADE CONSTRAINTS;

DROP TABLE vet CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE appointment (
    app_id           NUMBER(4) NOT NULL,
    app_paymethod    VARCHAR2(4) NOT NULL,
    app_totalamount  NUMBER(6, 2) NOT NULL,
    pet_id           NUMBER(3) NOT NULL,
    clinic_id        NUMBER(5) NOT NULL,
    vet_id           NUMBER(4) NOT NULL,
    app_datetime     DATE NOT NULL
);

ALTER TABLE appointment
    ADD CHECK ( app_paymethod IN ( 'Cash', 'EFT' ) );

COMMENT ON COLUMN appointment.app_id IS
    'surrigote key for appointment';

COMMENT ON COLUMN appointment.app_paymethod IS
    'Method of payment for appointment';

COMMENT ON COLUMN appointment.app_totalamount IS
    'Total cost of appointment including services and prescriptions';

COMMENT ON COLUMN appointment.pet_id IS
    'Unique Identifier of Pet';

COMMENT ON COLUMN appointment.clinic_id IS
    'Unique identifier for Clinic';

COMMENT ON COLUMN appointment.vet_id IS
    'Unique Identifier of Vetinarian';

COMMENT ON COLUMN appointment.app_datetime IS
    'Date and Time of appointment';

ALTER TABLE appointment ADD CONSTRAINT appointment_pk PRIMARY KEY ( app_id );

ALTER TABLE appointment ADD CONSTRAINT appointment_nk UNIQUE ( app_datetime,
                                                               vet_id );

CREATE TABLE clinic (
    clinic_id       NUMBER(5) NOT NULL,
    clinic_name     VARCHAR2(30) NOT NULL,
    clinic_phone    NUMBER(10) NOT NULL,
    clinic_address  VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN clinic.clinic_id IS
    'Unique identifier for Clinic';

COMMENT ON COLUMN clinic.clinic_name IS
    'Name of Clinic';

COMMENT ON COLUMN clinic.clinic_phone IS
    'Phone number of clinic';

COMMENT ON COLUMN clinic.clinic_address IS
    'Address of clinic';

ALTER TABLE clinic ADD CONSTRAINT clinic_pk PRIMARY KEY ( clinic_id );

CREATE TABLE drug (
    drug_id    NUMBER(3) NOT NULL,
    drug_name  VARCHAR2(50) NOT NULL,
    drug_cost  NUMBER(4, 2) NOT NULL
);

COMMENT ON COLUMN drug.drug_id IS
    'Unique identidier for drug';

COMMENT ON COLUMN drug.drug_name IS
    'Name of drug';

COMMENT ON COLUMN drug.drug_cost IS
    'Cost of prescribed drugs';

ALTER TABLE drug ADD CONSTRAINT drug_pk PRIMARY KEY ( drug_id );

CREATE TABLE ownership (
    owner_id       NUMBER(4) NOT NULL,
    owner_gname    VARCHAR2(50) NOT NULL,
    owner_fname    VARCHAR2(50) NOT NULL,
    owner_street   VARCHAR2(50) NOT NULL,
    owner_town     VARCHAR2(20) NOT NULL,
    owner_poscode  NUMBER(4) NOT NULL,
    vet_id         NUMBER(4) NOT NULL
);

COMMENT ON COLUMN ownership.owner_id IS
    'Unique identifier for owner';

COMMENT ON COLUMN ownership.owner_gname IS
    'Owner Given Name';

COMMENT ON COLUMN ownership.owner_fname IS
    'Owner Family Name';

COMMENT ON COLUMN ownership.owner_street IS
    'Street of owners residence';

COMMENT ON COLUMN ownership.owner_town IS
    'Town of owners residence';

COMMENT ON COLUMN ownership.owner_poscode IS
    'Postcode of owners residence';

COMMENT ON COLUMN ownership.vet_id IS
    'Unique Identifier of Vetinarian';

ALTER TABLE ownership ADD CONSTRAINT ownership_pk PRIMARY KEY ( owner_id );

CREATE TABLE pet (
    pet_id        NUMBER(3) NOT NULL,
    pet_gender    VARCHAR2(6) NOT NULL,
    pet_name      VARCHAR2(50) NOT NULL,
    pet_dob       DATE NOT NULL,
    pet_deceased  CHAR(1) NOT NULL,
    owner_id      NUMBER(4) NOT NULL,
    pettype_id    NUMBER(5) NOT NULL
);

ALTER TABLE pet
    ADD CHECK ( pet_gender IN ( 'Female', 'Male' ) );

ALTER TABLE pet
    ADD CHECK ( pet_deceased IN ( 'N', 'Y' ) );

COMMENT ON COLUMN pet.pet_id IS
    'Unique Identifier of Pet';

COMMENT ON COLUMN pet.pet_gender IS
    'Gender of pet';

COMMENT ON COLUMN pet.pet_name IS
    ' Name of Pet';

COMMENT ON COLUMN pet.pet_dob IS
    'The Pet''s date of birth';

COMMENT ON COLUMN pet.pet_deceased IS
    'Whether pet is deceased (Y if it is, N if it''s not)';

COMMENT ON COLUMN pet.owner_id IS
    'Unique identifier for owner';

COMMENT ON COLUMN pet.pettype_id IS
    'Uniquue identifier for pettype';

ALTER TABLE pet ADD CONSTRAINT pet_pk PRIMARY KEY ( pet_id );

CREATE TABLE pettype (
    pettype_id    NUMBER(5) NOT NULL,
    pettype_name  VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN pettype.pettype_id IS
    'Uniquue identifier for pettype';

COMMENT ON COLUMN pettype.pettype_name IS
    'Name fo pettype';

ALTER TABLE pettype ADD CONSTRAINT pettype_pk PRIMARY KEY ( pettype_id );

CREATE TABLE prescription (
    app_id     NUMBER(4) NOT NULL,
    drug_id    NUMBER(3) NOT NULL,
    drug_qty   NUMBER(3) NOT NULL,
    pres_cost  NUMBER(10, 2) NOT NULL,
    pres_dose  NUMBER(5) NOT NULL,
    pres_freq  VARCHAR2(20)
);

COMMENT ON COLUMN prescription.app_id IS
    'surrigote key for appointment';

COMMENT ON COLUMN prescription.drug_id IS
    'Unique identidier for drug';

COMMENT ON COLUMN prescription.drug_qty IS
    'Quantity of drug in prescription';

COMMENT ON COLUMN prescription.pres_cost IS
    'Cost of prescription';

COMMENT ON COLUMN prescription.pres_dose IS
    'Dose of drugs for prescription';

COMMENT ON COLUMN prescription.pres_freq IS
    'Frequency of drug use in prescription';

ALTER TABLE prescription ADD CONSTRAINT prescription_pk PRIMARY KEY ( app_id,
                                                                      drug_id );

CREATE TABLE procedure (
    app_id        NUMBER(4) NOT NULL,
    service_code  CHAR(5) NOT NULL
);

COMMENT ON COLUMN procedure.app_id IS
    'surrigote key for appointment';

COMMENT ON COLUMN procedure.service_code IS
    'Unique identifier for service';

ALTER TABLE procedure ADD CONSTRAINT procedure_pk PRIMARY KEY ( app_id,
                                                                service_code );

CREATE TABLE service (
    service_code         CHAR(5) NOT NULL,
    service_description  VARCHAR2(300) NOT NULL,
    service_cost         NUMBER(4, 2) NOT NULL
);

COMMENT ON COLUMN service.service_code IS
    'Unique identifier for service';

COMMENT ON COLUMN service.service_description IS
    'Short description of service';

COMMENT ON COLUMN service.service_cost IS
    'Cost of service';

ALTER TABLE service ADD CONSTRAINT service_pk PRIMARY KEY ( service_code );

CREATE TABLE specialisation (
    spec_id    NUMBER(4) NOT NULL,
    spec_name  VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN specialisation.spec_id IS
    'Unique Identifier for specialisation';

COMMENT ON COLUMN specialisation.spec_name IS
    'Name of Specialisation';

ALTER TABLE specialisation ADD CONSTRAINT specialisation_pk PRIMARY KEY ( spec_id );

CREATE TABLE vet (
    vet_id         NUMBER(4) NOT NULL,
    vet_name       VARCHAR2(50) NOT NULL,
    vet_phone      NUMBER(10) NOT NULL,
    vet_startdate  DATE NOT NULL,
    vet_gname      VARCHAR2(20) NOT NULL,
    vet_fname      VARCHAR2(20) NOT NULL,
    spec_id        NUMBER(4) NOT NULL,
    clinic_id      NUMBER(5) NOT NULL
);

COMMENT ON COLUMN vet.vet_id IS
    'Unique Identifier of Vetinarian';

COMMENT ON COLUMN vet.vet_name IS
    'Vetinarian Name';

COMMENT ON COLUMN vet.vet_phone IS
    'Phone number of vet';

COMMENT ON COLUMN vet.vet_startdate IS
    'Starting date for vet';

COMMENT ON COLUMN vet.vet_gname IS
    'Given name of vet';

COMMENT ON COLUMN vet.vet_fname IS
    'Family name of vet';

COMMENT ON COLUMN vet.spec_id IS
    'Unique Identifier for specialisation';

COMMENT ON COLUMN vet.clinic_id IS
    'Unique identifier for Clinic';

ALTER TABLE vet ADD CONSTRAINT vet_pk PRIMARY KEY ( vet_id );

ALTER TABLE appointment
    ADD CONSTRAINT appointment_pet FOREIGN KEY ( pet_id )
        REFERENCES pet ( pet_id );

ALTER TABLE prescription
    ADD CONSTRAINT appointment_prescription FOREIGN KEY ( app_id )
        REFERENCES appointment ( app_id );

ALTER TABLE procedure
    ADD CONSTRAINT appointment_procedure FOREIGN KEY ( app_id )
        REFERENCES appointment ( app_id );

ALTER TABLE appointment
    ADD CONSTRAINT clinic_appointment FOREIGN KEY ( clinic_id )
        REFERENCES clinic ( clinic_id );

ALTER TABLE vet
    ADD CONSTRAINT clinic_vet FOREIGN KEY ( clinic_id )
        REFERENCES clinic ( clinic_id );

ALTER TABLE prescription
    ADD CONSTRAINT drug_prescription FOREIGN KEY ( drug_id )
        REFERENCES drug ( drug_id );

ALTER TABLE pet
    ADD CONSTRAINT ownership_pet FOREIGN KEY ( owner_id )
        REFERENCES ownership ( owner_id );

ALTER TABLE pet
    ADD CONSTRAINT pettype_pet FOREIGN KEY ( pettype_id )
        REFERENCES pettype ( pettype_id );

ALTER TABLE procedure
    ADD CONSTRAINT service_procedure FOREIGN KEY ( service_code )
        REFERENCES service ( service_code );

ALTER TABLE vet
    ADD CONSTRAINT specialisation_vet FOREIGN KEY ( spec_id )
        REFERENCES specialisation ( spec_id );

ALTER TABLE appointment
    ADD CONSTRAINT vet_appointment FOREIGN KEY ( vet_id )
        REFERENCES vet ( vet_id );

ALTER TABLE ownership
    ADD CONSTRAINT vet_ownership FOREIGN KEY ( vet_id )
        REFERENCES vet ( vet_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             0
-- ALTER TABLE                             27
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0



SPOOL off
set echo off